config/routes.rb
Rails.application.routes.draw do
  resources :trucks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/profile/edit', to:'profiles#edit', as:'edit_profile'
  patch '/profile', to: 'profiles#update'


  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :events
  resources :jobs

  get "tickets/history:id" => "tickets#history", :as => 'history_ticket'
  post "tickets/search" => "tickets#search", :as => 'search_ticket'
  resources :tickets

  get "claims/history:id" => "claims#history", :as => 'history_claim'
  post "claims/begin:id" => "claims#begin", :as => 'begin_claim'
  resources :claims do
    member do
      post 'coordinate'
    end
  end

  get "teams/home_dir" => "teams#home_dir", :as => 'dir_team'
  get "teams/home_technician" => "teams#home_technician", :as => 'technician_team'
  get "teams/search" => "teams#search", :as => 'search_team'
  resources :teams

  get "dreports/end_shift:id" => "dreports#end_shift", :as => 'shift_dreport'
  get "dreports/current" => "dreports#current", :as => 'current_dreport'
  post "dreports/search" => "dreports#search", :as => 'search_dreport'
  resources :dreports do
    member do
      post 'close'
    end
  end

  root 'teams#home'

end

app/views/menus/_menu_dir.html.haml
#cn-wrapper.cn-wrapper
  %ul
    %li
      %a{"data-method" => "delete", :href => "/users/sign_out"}
        %i.fa.fa-power-off{:title =>"Sing out", "aria-hidden" => "true"}
    //%li{":class" => ""}
    //  current_class?(profile_path)&gt;
    //  %a{:href => "/teams/home_dir"}
    //    %i.fa.fa-line-chart{:title =>"Dashboard", "aria-hidden" => "true"}

    %li
      = link_to search_team_path, :remote => true do
        = fa_icon "search", class: "fa-lg", :title =>"New Team"

    - if current_page?(dir_team_path)
      %li
        = link_to new_team_path, :remote => true do
          = fa_icon "users", class: "fa-lg", :title =>"New Team"
    - else
      %li
        %a{:href => "/teams/home_dir"}
          %i.fa.fa-home{:title =>"Home", "aria-hidden" => "true"}

    %li
      %a{:href => "/events"}
        %i.fa.fa-calendar{:title =>"Calendar", "aria-hidden" => "true"}
    %li
      = link_to edit_profile_path, :remote => true do
        = fa_icon "user", class: "fa-lg", :title =>"Profile"
#cn-overlay.cn-overlay

app/views/menus/_menu_technical.html.erb
<div class="cn-wrapper" id="cn-wrapper">
   <ul>
       <li id="01" ><a href="#"><span class="icon-picture"></span></a></li>
       <li id="02" ><a href="#"><span class="icon-headphones"></span></a></li>
       <li id="03" ><a href="#"><span class="icon-home"></span></a></li>
       <li id="04" ><a href="#"><span class="icon-facetime-video"></span></a></li>
       <li id="05" ><a href="#"><span class="icon-envelope-alt"></span></a></li>
   </ul>
</div>

app/views/menus/_search.html.haml
.card-group
  .card.border-info
    .card-header.text-center
      .row
        .col-4
        .col-4
          %h6 Search
        .col-4
    .card-body.p-0
      %nav.nav.nav-tabs.nav-justified
        %a.nav-item.nav-link.active{"data-toggle" => "tab", :href => "#dreport"}
          = fa_icon "calendar", class: "fa-2x"
        %a.nav-item.nav-link{"data-toggle" => "tab", :href => "#history"}
          = fa_icon "address-book-o", class: "fa-2x"

      .tab-content
        #dreport.tab-pane.fade.show.active
          = render '/menus/search_dreport'

        #history.tab-pane.fade
          = render '/menus/search_client'

app/views/menus/_search_client.html.haml
.card-body.p-0.text-center
  %br
  = form_with url: search_ticket_path, :remote => true do |f|
    .card-body.p-0
      %table.table.table-striped
        %thead
          %tr.row.m-0
            %th.d-inline-block.col-6 Phone
            %th.d-inline-block.col-6 Sma
        %thead
          %tr.row.m-0
            %td.d-inline-block.col-6= f.number_field :nt, class: 'text-center'
            %td.d-inline-block.col-6= f.number_field :sma, class: 'text-center'
    .card-footer.p-0
      = button_tag(type: 'submit', class: "btn btn-outline-success") do
        = fa_icon "paper-outline-plane", text: "Search", right: true, class: "fa-lg"
      %br

app/views/menus/_search_dreport.html.haml
= form_with url: search_dreport_path, :remote => true do |f|
  .card-body.p-0.text-center
    %p Date
    = f.date_field :date
  .card-footer.text-center
    = button_tag(type: 'submit', class: "btn btn-outline-success") do
      = fa_icon "paper-plane", text: "Search", right: true, class: "fa-lg"