config/routes.rb
Rails.application.routes.draw do
  resources :trucks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/profile/edit', to:'profiles#edit', as:'edit_profile'
  patch '/profile', to: 'profiles#update'


  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :events
  resources :jobs

  get "tickets/history:id" => "tickets#history", :as => 'history_ticket'
  post "tickets/search" => "tickets#search", :as => 'search_ticket'
  resources :tickets

  get "claims/history:id" => "claims#history", :as => 'history_claim'
  post "claims/begin:id" => "claims#begin", :as => 'begin_claim'
  resources :claims do
    member do
      post 'coordinate'
    end
  end

  get "teams/home_dir" => "teams#home_dir", :as => 'dir_team'
  get "teams/home_technician" => "teams#home_technician", :as => 'technician_team'
  get "teams/search" => "teams#search", :as => 'search_team'
  resources :teams

  get "dreports/end_shift:id" => "dreports#end_shift", :as => 'shift_dreport'
  get "dreports/current" => "dreports#current", :as => 'current_dreport'
  post "dreports/search" => "dreports#search", :as => 'search_dreport'
  resources :dreports do
    member do
      post 'close'
    end
  end

  root 'teams#home'

end

app/models/dreport.rb
class Dreport < ApplicationRecord

  #---------- Associations ----------#

  # => relation 1:N  -  dreport tickets
  has_many :tickets

  # => relation n:m dreports_users
  has_and_belongs_to_many :users

  #---------- Public Method´s ----------#

  # => return collection of tickets order to starts_at ASC
  def tickets_order_start_at
    tickets.order( 'starts_at ASC' )
  end

  # => return true if self closed
  def closed?
    closed == true
  end

  # => change status to closed true
  def to_close
    self.closed = true
    save
  end

  # => return data from responsables
  def data_responsables
    data = []
    data << users.first.email
    unless has_responsable?
      data << users.second.email
    end
    return data
  end

  # => return true or false if contain only one responsable
  def has_responsable?
    users.count == 1
  end

  # => load a team parameters to dreport
  def load_parameters(team)
    self.date = team.date
    self.truck = team.truck.number
    self.brand = team.truck.brand
    self.add_responsables(team)

    claims = team.claims.concluded
    unless claims.nil?
      self.association_tickets(claims)
    end
    save
  end

  # => pretty print
  def date_format
    date.strftime("%d/%m/%Y")
  end

  #---------- Private Method´s ----------#

  # => load responsables to dreport
  def add_responsables(team)
    self.users << team.responsables.first
    unless team.has_responsable?
      self.users << team.responsables.second
    end
  end

  # => create and associated tickets
  def association_tickets(claims)
    claims.each do |claim|
      #create new ticket
      @ticket = Ticket.new
      #load simple attributes
      @ticket.load_parameters(claim)
      @ticket.dreport_association(self)
    end
  end

  # => scope dreport today
  scope :today, lambda { where('date = ?', Date.today) }
  # => scope dreport today
  scope :date, -> (date_param) { where('date = ?', date_param) }
end

app/controllers/dreports_controller.rb
class DreportsController < ApplicationController
  before_action :set_dreport, only: [:show, :edit, :update, :destroy]

  def search
    date_param = params["date"]
    dreports_date = []
    unless date_param.empty?
      dreports_date = Dreport.date(date_param)
    end
    @dreports = dreports_date
  end

  def index
    authorize Dreport
    @dreports = Dreport.today
  end

  # => close to dreport
  def close
    authorize Dreport
    news_param =  params["news"]
    dreport = Dreport.find(params[:id])
    dreport.to_close
    dreport.news = news_param
    dreport.save!
    redirect_to technician_team_path
  end

  # => finish day
  def end_shift
    authorize Dreport
    team = Team.find(params[:id])
    @dreport = Dreport.new
    @dreport.save!
    @dreport.load_parameters(team)
    team.finalize
    redirect_to dreport_path(@dreport)
  end

  def show
    authorize Dreport
    @dreport = Dreport.find(params[:id])
  end

  def current
    authorize Dreport
    @dreport = current_user.dreports.last
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_dreport
    @dreport = Dreport.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def dreport_params
    params
      .require(:dreport)
      .permit(
        {:team_ids =>[]}
      )
  end

end

app/helpers/dreports_helper.rb
module DreportsHelper
  def dreport_responsables(dreport)
    if dreport.users.second.nil?
      dreport.users.first.email
    else
      dreport.users.first.email + " - " + dreport.users.second.email
    end
  end

  def dreport_truck(dreport)
    dreport.brand + " Nº" + dreport.truck.to_s
  end
end

app/views/dreports/_dialog.html.haml
= render "/layouts/dialog"

app/views/dreports/_dreport.html.haml
.card-group.card-dreport
  .card.border-info
    .card-header.text-center
      = dreport_responsables(dreport) + " #{dreport.brand} " + "#{dreport.truck}"
      %span.btn.btn-default
      %i{class: "fa fa-angle-double-down btn btn-outline-primary","aria-controls" => "dreport_#{dreport.id}", "aria-expanded" => "true", "data-target" => "#dreport#{dreport.id}", "data-toggle" => "collapse"}


    .collapse{:id => ("dreport#{dreport.id}"), "aria-labelledby" => "heading#{dreport.id}", "data-parent" => "#accordion"}
      .card-body.text-center

        - dreport.tickets_order_start_at.each do |ticket|
          .card-group
            .card.card-dreport-container
              .card.card-dreport-data
                %table.table.table-striped
                  %thead
                    %tr.row.m-0
                      %th.d-inline-block.col-3 Nº Ticket
                      %th.d-inline-block.col-3 Client
                      %th.d-inline-block.col-2 Status
                      %th.d-inline-block.col-2 Type
                      %th.d-inline-block.col-2 Hour
                  %thead
                    %tr.row.m-0
                      %td.d-inline-block.col-3= "#{ticket.number}"
                      %td.d-inline-block.col-3= "#{ticket.client}"
                      %td.d-inline-block.col-2= "#{ticket.status}"
                      %td.d-inline-block.col-2= "#{ticket.kind}"
                      %td.d-inline-block.col-2= "#{ticket.starts}" + " " + "#{ticket.end}"
              .card.card-dreport
                .row
                  .col-4
                  .col-4
                    %p Observation
                  .col-4
                    .float-right
                      = link_to ticket_path(ticket), :remote => true do
                        = fa_icon "eye", right: true, class: "fa-lg btn btn-outline-info"
                      &nbsp
                      - if ticket.has_history?
                        = link_to history_ticket_path(ticket) do
                          = fa_icon "history", class: "fa-lg btn btn-outline-info"
              .card-body.p-0
                %p= "#{ticket.observation}"

    .card.card-dreport  News
    .card-body
      %p= "#{dreport.news}"

app/views/dreports/_dreport_ticket_data.html.haml
.card-group
  .card.border-info
    .card.card-dreport
      %table
        %td.align-middle Cliente :
        %td.align-middle "382577"
        %td.align-middle Estado :
        %td.align-middle finalizado
        %td.align-middle Tipo :
        %td.align-middle Reclamo
    .card.card-dreport Observacion
    .card-body.p-0
      %p Reclamo finalizado

app/views/dreports/_search.html.haml
.text-center
  .row
    .col-4
    .col-4
      - if !@dreports.empty?
        = @dreports.first.date_format
      - else
        %h6 There are no reports

      %br

  .card-group
    .card-body
      = render @dreports

app/views/dreports/_show.html.haml
= render 'dialog'
.container.text-center.container-dreport-show
  .card-group
    %tbody
      .card-group.card-dreport.card-dreport-show
        .card.border-info
          .card-header.text-center
            = dreport_responsables(@dreport)
            %br
            = @dreport.brand
            =@dreport.truck
          .card-body.text-center
            - @dreport.tickets_order_start_at.each do |ticket|
              .card-group
                .card.card-dreport-container
                  .card.card-dreport-data
                    %table.table.table-striped
                      %thead
                        %tr.row.m-0
                          %th.d-inline-block.col-3 Nº ticket
                          %th.d-inline-block.col-3 Client
                          %th.d-inline-block.col-3 Type
                          %th.d-inline-block.col-3 Hour
                      %thead
                        %tr.row.m-0
                          %td.d-inline-block.col-3= "#{ticket.number}"
                          %td.d-inline-block.col-3= "#{ticket.client}"
                          %td.d-inline-block.col-3= "#{ticket.kind}"

                          %td.d-inline-block.col-3= "#{ticket.starts}" + " " + "#{ticket.end}"
                  .card.card-dreport
                    .row
                      .col-4
                      .col-4
                        %p Observation
                      .col-4

                  .card-body.p-0
                    %p= "#{ticket.observation}"
                  .card-footer
                    = link_to ticket_path(ticket), :remote => true do
                      = fa_icon "eye", right: true, class: "fa-lg btn btn-outline-info"
                    &nbsp
                    - if ticket.has_history?
                      = link_to history_ticket_path(ticket) do
                        = fa_icon "history", class: "fa-lg btn btn-outline-info"

          - if @dreport.closed?
            .card.card-dreport News
            .card-body
              %p= "#{@dreport.news}"
          - else
            .card
              .card News
              .card-body.p-0.text-center
                %br
                = form_with url: close_dreport_path(@dreport) do |f|
                  = f.text_area :news
                  %br
                  = button_tag(type: 'submit', class: "btn btn-success") do
                    = fa_icon "paper-plane", text: "Send", right: true, class: "fa-lg"
                %br

app/views/dreports/current.html.haml
%p= "#{@dreport.id}"

app/views/dreports/end_shift.html.haml
%p "#{@dreport.date_format}"
%p= dreport_truck(@dreport)
%p= dreport_responsables(@dreport)
- @dreport.tickets.each do |ticket|
  %p=  ticket.number
  %p=  ticket.client
  %p=  ticket.start
  %p=  ticket.end
  %p=  ticket.kind


  - ticket.job_codes.each do |job_cod|
    = "Job code: " + "#{job_cod}"
  %br

  - ticket.job_titles.each do |job_title|
    = "Job title: " + "#{job_title}"
  %br

  - ticket.mat_items.each do |mat_item|
    = "Item: " + "#{mat_item}"

  - ticket.mat_qtys.each do |mat_qty|
    = "Quantity: " + "#{mat_qty}"
  %br

  - ticket.meas_points.each do |meas_point|
    = "Point:" + "#{meas_point}"
  %br

  - ticket.meas_logs.each do |meas_log|
    = "Log:" + "#{meas_log}"
  %br

  %p=  ticket.status
  %p=  ticket.author
  %p=  ticket.observation
= link_to @dreport.truck , dreport_path(@dreport)

app/views/dreports/index.html.haml
= render 'dialog'
.container.text-center
  .row
    .col-4
    .col-8
      = render 'teams/clock'
      %br

  .card-group
    %tbody
      = render @dreports

app/views/dreports/search.js.erb
// Add the dialog title
$('#dialog h3').html(" <i class='fa fa-search'></i>");

// Render the new form
$('.modal-body').html('<%= j render("search") %>');


// Show the dynamic dialog
$('#dialog').modal("show");
$('.container.text-center').css('visibility', 'hidden');


$('#dialog').on('hidden.bs.modal', function () {
  $('.container.text-center').css('visibility', 'visible');
});

app/views/dreports/show.html.haml
= render 'show'