config/routes.rb
Rails.application.routes.draw do
  resources :trucks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/profile/edit', to:'profiles#edit', as:'edit_profile'
  patch '/profile', to: 'profiles#update'


  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :events
  resources :jobs

  get "tickets/history:id" => "tickets#history", :as => 'history_ticket'
  post "tickets/search" => "tickets#search", :as => 'search_ticket'
  resources :tickets

  get "claims/history:id" => "claims#history", :as => 'history_claim'
  post "claims/begin:id" => "claims#begin", :as => 'begin_claim'
  resources :claims do
    member do
      post 'coordinate'
    end
  end

  get "teams/home_dir" => "teams#home_dir", :as => 'dir_team'
  get "teams/home_technician" => "teams#home_technician", :as => 'technician_team'
  get "teams/search" => "teams#search", :as => 'search_team'
  resources :teams

  get "dreports/end_shift:id" => "dreports#end_shift", :as => 'shift_dreport'
  get "dreports/current" => "dreports#current", :as => 'current_dreport'
  post "dreports/search" => "dreports#search", :as => 'search_dreport'
  resources :dreports do
    member do
      post 'close'
    end
  end

  root 'teams#home'

end

app/models/truck.rb
class Truck < ApplicationRecord

  #---------- Associations ----------#

  #relation 1:N  -  truck teams
  has_many :teams


end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]

  def index
    @trucks = Truck.all
  end

  def show
  end

  def new
    @truck = Truck.new
  end

  def edit
  end

  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: 'Truck was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(:number, :brand)
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= simple_form_for(@truck) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :brand %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trucks</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.number %></td>
        <td><%= truck.brand %></td>
        <td><%= link_to 'Show', truck %></td>
        <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
        <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @truck.number %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @truck.brand %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>